Задание 1

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;
AB - не определено;
BA - не определено;
б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;
AB - размерность 2x3;
BA - не определено;
в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;
AB - размерность 8x8;
BA - размерность 3x3;
г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 ;
AB - размерность 4x4;
BA - размерность 4x4;

Задание 2

In [1]:
import numpy as np
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(a+b)

[[ 5 -3]
 [ 3  5]]


In [2]:
print(np.dot(a,b))

[[  4 -11]
 [ 12  -3]]


In [3]:
print(np.dot(b,a))

[[ 1 -8]
 [15  0]]


Задание 3

In [4]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(3*a+b*(-2)+4*c)

[[ 11  -5]
 [  9 -12]]


Задание 4

In [5]:
a = np.array([[4, 1], [5, -2], [2, 3]])
a.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [8]:
print(np.dot(a,(a.T)))
print(np.dot((a.T),a))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]
