Задание 1 вариант а невозможно проверить в пайтон?

In [5]:
#б
import numpy as np
import scipy.linalg
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(a)
print(np.linalg.det(a))

[[4 2 3]
 [0 5 1]
 [0 0 9]]
180.0


In [11]:
#в
import numpy as np
import scipy.linalg
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(f'{np.linalg.det(a):.0f}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-0


Задание 2

In [15]:
import numpy as np
import scipy.linalg
a = np.array([[1, 2, 3], [4, 2, 8], [3, 5, 7]])
b = a @ a
print(b)
print(f'{np.linalg.det(a):.0f}')
print(f'{np.linalg.det(b):.0f}')

[[18 21 40]
 [36 52 84]
 [44 51 98]]
8
64


In [16]:
import numpy as np
import scipy.linalg
a = np.array([[1, 2, 3], [4, 2, 8], [3, 5, 7]])
b = a.T
print(b)
print(f'{np.linalg.det(a):.0f}')
print(f'{np.linalg.det(b):.0f}')

[[1 4 3]
 [2 2 5]
 [3 8 7]]
8
8


In [17]:
import numpy as np
import scipy.linalg
a = np.array([[1, 2, 3], [4, 2, 8], [3, 5, 7]])
b = 2 * a 
print(b)
print(f'{np.linalg.det(a):.0f}')
print(f'{np.linalg.det(b):.0f}')

[[ 2  4  6]
 [ 8  4 16]
 [ 6 10 14]]
8
64


Задание 3

In [18]:
import numpy as np
import scipy.linalg
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(a)
print(f'{np.linalg.det(a):.0f}')

[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
0


Задание 4

In [19]:
import numpy as np
import scipy.linalg
a = np.array([[-1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(a)
print(np.linalg.matrix_rank(a))

[[-1  2  3]
 [ 1  1  1]
 [ 2  3  4]]
3


In [20]:
import numpy as np
import scipy.linalg
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(a)
print(np.linalg.matrix_rank(a))

[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
3
